dist: trusty
sudo: false
language: c
compiler:
- gcc
- clang
addons:
  apt:
    packages:
    - docbook-xml
    - docbook-xsl
    - libxml2-utils
    - linux-libc-dev
    - xsltproc
script:
- make
- make -C doc validate all

# vim:ts=2 sts=2 sw=2 et
